name: 'F5 WAF policy apply'
description: 'Appply imported and uploaded WAF policy in F5 BIG-IP'
inputs:
  waf-address:  
    description: 'Address of F5 WAF instance'
    required: true
  username:  
    description: 'f5 big-ip username'
    required: true
  password:  
    description: 'f5 big-ip user's password'
    required: true
  policy-name:  
    description: 'Name of the uploaded policy'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'