name: 'F5 WAF vulnerability scan'
description: 'Verifying what kind of traffic is possible to pass by the current WAF policy'
inputs:
  waf-address:  
    description: 'Address of F5 WAF instance'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'